on:
    release:
        types: [created]

permissions:
    contents: write
    packages: write

jobs:
    release-confs:
        name: Release configs and templates
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Upload files to release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh release upload ${{ github.event.release.tag_name }} smpm.conf template.xml

    release-matrix:
        name: Release binaries
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows]
                goarch: ["386", amd64]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Build release  
              uses: wangyoucao577/go-release-action@v1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                goos: ${{ matrix.goos }}
                goarch: ${{ matrix.goarch }}
                goversion: "https://go.dev/dl/go1.26.7.linux-amd64.tar.gz"
                project_path: "."
                binary_name: "smpm"
                ldflags: "-s -w"
                build_flags: "-gcflags=all=-l"
                compress_assets: "OFF"
